<a href="https://colab.research.google.com/github/smsmorsalin/ML-Basics/blob/main/Basic_of_json_and_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Local Json File

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_json("/content/one_piece.json")

In [ ]:
df

,Unnamed: 0,rank,trend,season,episode,name,start,total_votes,average_rating
0,0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
...,...,...,...,...,...,...,...,...,...
953,953,"41,448",26,1,954,Its Name is Enma! Oden's Meito!,2020,302,7.7
954,954,"35,342",44,1,955,&quot;A New Alliance?! Kaido's Army Gathers&quot;,2020,407,7.4
955,955,"33,715",75,1,956,Ticking Down to the Great Battle! The Straw Ha...,2020,353,8.2
956,956,"2,940",964,1,957,Big News! The Warlords Attack Incident,2021,"2,862",9.1
957,957,"14,751",-,1,958,&quot;The Legendary Battle! Garp and Roger&quot;,2021,746,9.4

# Online json file

In [ ]:
df = pd.read_json("https://storage.googleapis.com/kagglesdsdata/datasets/1108393/1862570/One%20Piece%20json.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260623%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260623T170049Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=1314a91ac632ce77d01f3cb168e9733317c61303142c5aad4ecdf5be1e9d62ee46fbc7a842b1b565fbe0be7771bb35561aa4d68f47469f8e8e9ca0cb36d3b182f600346807b89a3a14935a1432e760356e5e1f89ddf2f67ceaf1d243081a782715e19394ad62136df65367f55aceab9f89b0e5876101dcf53221586093e5576b6e07f6634e3beb3a28d2b49b056ed23d29eb309a3c1d8d15a2de2eb65a41bfa0508506e7109e758ab1799d84ea028d0f731c12f350fead196ccbae508dd40fb7d22c38297030e5d7f11abc91527ac7d96c0eb99c633b3a796358ea0d201d22d663b926f7f7d79f6cdfc3a84a6f40065b44281a949fa2b803130aee4aa24c8405")
df

,Unnamed: 0,rank,trend,season,episode,name,start,total_votes,average_rating
0,0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
...,...,...,...,...,...,...,...,...,...
953,953,"41,448",26,1,954,Its Name is Enma! Oden's Meito!,2020,302,7.7
954,954,"35,342",44,1,955,&quot;A New Alliance?! Kaido's Army Gathers&quot;,2020,407,7.4
955,955,"33,715",75,1,956,Ticking Down to the Great Battle! The Straw Ha...,2020,353,8.2
956,956,"2,940",964,1,957,Big News! The Warlords Attack Incident,2021,"2,862",9.1
957,957,"14,751",-,1,958,&quot;The Legendary Battle! Garp and Roger&quot;,2021,746,9.4

# Working with SQL File

In [ ]:
# 1. load the sql file in XAMPP
# 2. install mysql.connector
# 3. import mysql
# 4. connect with XAMPP localhost and specific database.

# below have an example:

In [ ]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 96.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-linux_x86_64.whl size=247950 sha256=2aaf09cc12719aa23f7e253dac06dbaf2e5f6e6a94b0b39c411dd8cefb16c41c
  Stored in directory: /root/.cache/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [ ]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(host="localhost", user="root", password='', database="database_name")

In [ ]:
df = pd.read_sql_query("select * from table_name", conn)
df