<a href="https://colab.research.google.com/github/smsmorsalin/ML-Basics/blob/main/Basic_of_CSV_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import method**

In [81]:
import kagglehub
import pandas as pd

# **Open Local CSV File**

In [82]:
df = pd.read_csv('/content/match_events.csv')
df

     event_id  match_id  minute   event_type  team_id  player_id
0           1         1       9         Goal        1         16
1           2         1      25  Yellow Card        2         44
2           3         1      44  Yellow Card        1         11
3           4         1      47  Yellow Card        1         16
4           5         1      55     Red Card        2         39
..        ...       ...     ...          ...      ...        ...
178       179        28      80     Red Card        6        134
179       180        28      84         Goal        8        199
180       181        28      90         Goal        8        191
181       182        28      90         Goal        8        192
182       183        28      90         Goal        6        156

[183 rows x 6 columns]

## **Openning a CSV file From Online URL**

In [83]:
from io import StringIO
import requests

# past the link of the csv file here
url = "https://github.com/plotly/datasets/blob/master/earthquake.csv"
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}

# Fetch the webpage data using the custom headers
req = requests.get(url, headers=headers)

# Wrap the text in StringIO so pandas can read it like a file
data = StringIO(req.text)

# Load into a DataFrame (cmnt out below code to run)
# df = pd.read_csv(data)

# dealing with TSV files

In [84]:
df = pd.read_csv("/content/web_traffic.tsv", sep="\t")
df

      0.0   1590.0
0     1.0   2130.0
1     2.0   3221.0
2     3.0   4221.0
3     4.0   5171.0
4     5.0   5762.0
..    ...      ...
738  19.0  17984.0
739  20.0  18111.0
740  21.0  16935.0
741  22.0  16337.0
742  23.0  15695.0

[743 rows x 2 columns]

# Seperate Parameters

In [85]:
# if the header of the column is not initialize then use this to name the coulmn header .

df = pd.read_csv("/content/web_traffic.tsv", sep="\t", names=["Day", "Visitors", "Bounce Rate"])
df

      Day  Visitors  Bounce Rate
0     0.0    1590.0          NaN
1     1.0    2130.0          NaN
2     2.0    3221.0          NaN
3     3.0    4221.0          NaN
4     4.0    5171.0          NaN
..    ...       ...          ...
739  19.0   17984.0          NaN
740  20.0   18111.0          NaN
741  21.0   16935.0          NaN
742  22.0   16337.0          NaN
743  23.0   15695.0          NaN

[744 rows x 3 columns]

# Index Col parameter

In [86]:
df = pd.read_csv(
    "/content/web_traffic.tsv",
    sep="\t",
    names=["Day", "Visitors", "Bounce Rate"],
    index_col="Day"
    )
df

      Visitors  Bounce Rate
Day
0.0     1590.0          NaN
1.0     2130.0          NaN
2.0     3221.0          NaN
3.0     4221.0          NaN
4.0     5171.0          NaN
...        ...          ...
19.0   17984.0          NaN
20.0   18111.0          NaN
21.0   16935.0          NaN
22.0   16337.0          NaN
23.0   15695.0          NaN

[744 rows x 2 columns]

# header parameter

In [87]:
# if the header of the column is the next row/ if want to delete first row/n rows then use it:

df = pd.read_csv(
    "/content/match_events.csv",
    header=1
    )
df

       1  1.1   9         Goal  1.2   16
0      2    1  25  Yellow Card    2   44
1      3    1  44  Yellow Card    1   11
2      4    1  47  Yellow Card    1   16
3      5    1  55     Red Card    2   39
4      6    1  55   VAR Review    2   39
..   ...  ...  ..          ...  ...  ...
177  179   28  80     Red Card    6  134
178  180   28  84         Goal    8  199
179  181   28  90         Goal    8  191
180  182   28  90         Goal    8  192
181  183   28  90         Goal    6  156

[182 rows x 6 columns]

# Use specific column

In [88]:
# to select specific column use this:
df = pd.read_csv("/content/match_events.csv", usecols=["match_id", "minute", "event_type"])
df

     match_id  minute   event_type
0           1       9         Goal
1           1      25  Yellow Card
2           1      44  Yellow Card
3           1      47  Yellow Card
4           1      55     Red Card
..        ...     ...          ...
178        28      80     Red Card
179        28      84         Goal
180        28      90         Goal
181        28      90         Goal
182        28      90         Goal

[183 rows x 3 columns]

# Squeze Parameter

In [89]:
#if need just one column
# df = pd.read_csv("/content/match_events.csv", usecols=["match_id"], squeeze=True)
# df

# Skip Rows

In [90]:
# To skip any spcific rows:

df = pd.read_csv("/content/match_events.csv", skiprows=[1,2])
#the 1 and 2 column will be skip
df

     event_id  match_id  minute   event_type  team_id  player_id
0           3         1      44  Yellow Card        1         11
1           4         1      47  Yellow Card        1         16
2           5         1      55     Red Card        2         39
3           6         1      55   VAR Review        2         39
4           7         1      55  Yellow Card        1         11
..        ...       ...     ...          ...      ...        ...
176       179        28      80     Red Card        6        134
177       180        28      84         Goal        8        199
178       181        28      90         Goal        8        191
179       182        28      90         Goal        8        192
180       183        28      90         Goal        6        156

[181 rows x 6 columns]

# N Rows

In [91]:
#to show only specific rows:

df = pd.read_csv("/content/match_events.csv", nrows=5)
#this will show only 5 rows
df

   event_id  match_id  minute   event_type  team_id  player_id
0         1         1       9         Goal        1         16
1         2         1      25  Yellow Card        2         44
2         3         1      44  Yellow Card        1         11
3         4         1      47  Yellow Card        1         16
4         5         1      55     Red Card        2         39

# encoding

In [92]:
#past the encoding type, if the data is encoded
df = pd.read_csv("/content/match_events.csv", encoding="")

# skip bad lines

In [93]:
# df = pd.read_csv(
#     "/content/web_traffic.tsv",
#     sep="\t",
#     error_bad_lines=False
#     )
# df

# Dtypes

In [94]:
#convert the type

df = pd.read_csv("/content/match_events.csv", dtype={"minute": "float"})
df

     event_id  match_id  minute   event_type  team_id  player_id
0           1         1     9.0         Goal        1         16
1           2         1    25.0  Yellow Card        2         44
2           3         1    44.0  Yellow Card        1         11
3           4         1    47.0  Yellow Card        1         16
4           5         1    55.0     Red Card        2         39
..        ...       ...     ...          ...      ...        ...
178       179        28    80.0     Red Card        6        134
179       180        28    84.0         Goal        8        199
180       181        28    90.0         Goal        8        191
181       182        28    90.0         Goal        8        192
182       183        28    90.0         Goal        6        156

[183 rows x 6 columns]

# #handling dates

In [95]:
#to convert dates type

df = pd.read_csv("/content/match_events.csv", parse_dates=["minute"])
#it's not working here because my minute column is not dates value
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   event_id    183 non-null    int64
 1   match_id    183 non-null    int64
 2   minute      183 non-null    object
 3   event_type  183 non-null    object
 4   team_id     183 non-null    int64
 5   player_id   183 non-null    int64
dtypes: int64(4), object(2)
memory usage: 8.7+ KB

/tmp/ipykernel_1916/2676370311.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("/content/match_events.csv", parse_dates=["minute"])

# #converter

In [96]:
def rename(data):
  if data == "Yellow Card":
    return 'YC'
  if data == "Red Card":
    return 'RC'
  return data

df = pd.read_csv("/content/match_events.csv", converters={"event_type": rename})
df

     event_id  match_id  minute event_type  team_id  player_id
0           1         1       9       Goal        1         16
1           2         1      25         YC        2         44
2           3         1      44         YC        1         11
3           4         1      47         YC        1         16
4           5         1      55         RC        2         39
..        ...       ...     ...        ...      ...        ...
178       179        28      80         RC        6        134
179       180        28      84       Goal        8        199
180       181        28      90       Goal        8        191
181       182        28      90       Goal        8        192
182       183        28      90       Goal        6        156

[183 rows x 6 columns]

# N/A values

In [97]:
df = pd.read_csv("/content/match_events.csv", na_values=["Goal"])
#it will convert Goal into NaH
df

     event_id  match_id  minute   event_type  team_id  player_id
0           1         1       9          NaN        1         16
1           2         1      25  Yellow Card        2         44
2           3         1      44  Yellow Card        1         11
3           4         1      47  Yellow Card        1         16
4           5         1      55     Red Card        2         39
..        ...       ...     ...          ...      ...        ...
178       179        28      80     Red Card        6        134
179       180        28      84          NaN        8        199
180       181        28      90          NaN        8        191
181       182        28      90          NaN        8        192
182       183        28      90          NaN        6        156

[183 rows x 6 columns]

# Loading A huge dataset/ divide into chunks

In [99]:
df = pd.read_csv("/content/match_events.csv", chunksize=60)
# divide into chunks every chunks have 60 elements/rows
for chunk in df:
  print(chunk.size)

360
360
360
18